# Generated by Django 5.1.1 on 2024-11-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_username'),
        ('users', '0003_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
    ]
